name: C/C++ CI

on:
  push:
    branches: '*'  
  pull_request:
    branches: '*'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install unbuffer
      run: sudo apt-get install expect
    - name: make
      run: make
    - name: make check
      run: make check
